### ISSUE TITLE
"No SSH SOCK AVAILABLE" when running sidekick init

### ISSUE THREAD

**Issue by NeverVane** [MightyMoud/sidekick#10]
Hi, I cloned your repo and compiled it.
When running `sidekick init` after providing all the needed info I get `No SSH SOCK AVAILABLE` . 
I think I could be missing something very obvious, but I'm on a fresh Ubuntu 22.04 install and can't get around.
Could you help?

**Comment by NeverVane** [comment]
Of course SSH service are up and running and keys are being generated

**Comment by MightyMoud** [comment]
Can you make sure the key is added to the agent? that's my wild guess. If that doesn't work, can you send a screenshot? wanna see which line causes this error to have a deeper look

**Comment by darrylmorley** [comment]
> I upgraded te agent and it was solved.

I'm having the same issue here, could you let me know what you mean by 'upgraded the agent please'?
