### ISSUE TITLE
Allow github repos instead of docker registry

### ISSUE THREAD

**Issue by zackees** [MightyMoud/sidekick#12]
My orgs infrastructure is 100% dockerfile driven on github repos. We redeploy on git pushes.

It would be nice if a user could put in a repo url to get an image built. The whole redeploy on Git push may be out of scope.

**Comment by MightyMoud** [comment]
In Sidekick now, the images are built locally on your machine. No CICD integration is done. 

> It would be nice if a user could put in a repo url to get an image built. 
>
Do you mean that we clone the repo, build locally and then use the resulting image? or do you mean build on CICD from that repo then use the image?

**Comment by zackees** [comment]
Clone the repo locally then build.

This is how Render.com and DigitalOcean do it. It's awesome as long as you pin your deps. Which was easy with npm and now also with python via uv.

It allows us to just hit the repo again and again during dev without a gig payload to transfer.

We are hitting it with micro commits and seeing if it breaks and when.

**Comment by MightyMoud** [comment]
So if you mean clone the repo locally on your laptop, then I think that would be on the dev himself to do that. Then run `sidekick launch` there.

I think Render.com would clone the repo to your VPS or basically to your server. Coolify also does the same thing.

I believe your source code doesn't belong to your Prod machine; only a docker image is needed. It's far simpler to build on your laptop, or CICD maybe, then push images there.

**Comment by zackees** [comment]
I mean that the service watches github for repo changes, then rebuilds when there's a change.

So setting a service is as easy as putting in a github url.

**Comment by MightyMoud** [comment]
@zackees I see what you mean now. I think that would be beyond the current scope of Sidekick. 
Happy to consider it again maybe before V1 release

**Comment by MightyMoud** [comment]
Closing this as it's not planned atm
