### ISSUE TITLE
Can Sidekick deploy to multiple VPS with one command like Fly.io?

### ISSUE THREAD

**Issue by honeyhead** [MightyMoud/sidekick#13]
I’ve been using Fly.io and love it, but I have several mini PCs at home, work, and even in different regions that I want to utilize. Fly.io allows me to specify the region and the number of instances to deploy across, and it manages the load balancing under one address.

If Sidekick can offer similar functionality, I’d be thrilled! I could reduce my Fly.io costs significantly, and I’d gladly support a paid version if this feature was included. Is there any plan to develop this?

**Comment by MightyMoud** [comment]
Hi @honeyhead,

Yeah that would be super cool. I like the vision of a feature like this and it is doable. 
However, I don't think it's something that I can squeeze in before V1 release tbh. There is still a lot more things I need to get in first before this kind of features is in focus.

**Comment by MightyMoud** [comment]
I'm closing this as it's not planned at the moment.
