### ISSUE TITLE
Stuck trying to adding the user.

### ISSUE THREAD

**Issue by lfpicoloto1** [MightyMoud/sidekick#19]
Hey!

I'm trying to use, and the sidekick get stuck trying to adding the user:
Any idea how can I solve this? Or what going on?

**Comment by MightyMoud** [comment]
Hey  @lfpicoloto1,

Could you supply more details please?
What OS is your VPS on? What version exactly? What OS are you on? and If you are getting any errors in the console? Otherwise it's hard for me help you

**Comment by lfpicoloto1** [comment]
Hi!

Im running in Ubuntu 22.04.4 LTS (my machine).
Remote machine: Ubuntu 22.04.5 LTS

No errors, just  get stuck trying to adding the user:
![image](https://github.com/user-attachments/assets/26c9eb2d-ee1b-40e6-8e17-2ac60def4808)

**Comment by MightyMoud** [comment]
@lfpicoloto1 Sadly I can't tell what's wrong.... I will work on improving our error reporting soon. For now it's just a black box. Things like this will get better with time @lfpicoloto1
