### ISSUE TITLE
Document lack of host Key validation

### ISSUE THREAD

**Issue by DanielleMaywood** [MightyMoud/sidekick#2]
I noticed you do not perform host key validation. Maybe this should be made more obvious to users without having to dig through the source?

https://github.com/MightyMoud/sidekick/blob/b99b61bd61d11d34d35d76bf4fc6f3c49651bd80/utils/utils.go#L77-L80

**Comment by MightyMoud** [comment]
Yup fair point. I honestly didn't expect anyone to actually use this... 
Thanks for pointing that out. I'll address this soon.

**Comment by lpil** [comment]
Forgive me, I'm not familiar with this library. What is one expected to do in this callback?

**Comment by DanielleMaywood** [comment]
> Forgive me, I'm not familiar with this library. What is one expected to do in this callback?

So you're expected to check if the `key` matches what you expect by checking the `.ssh/known_hosts` file or some other source of truth.

You can use a library like https://pkg.go.dev/golang.org/x/crypto/ssh/knownhosts or https://pkg.go.dev/github.com/skeema/knownhosts for making that easier.

**Comment by MightyMoud** [comment]
You both are too kind! 🙂 

I understand how critical this is now after some research. 
I'll open a PR tonight. I would be glad if you guys can review it to make sure I get this right. 

Let me know if you're keen, I'll assign you then...

**Comment by DanielleMaywood** [comment]
I'm more than happy to check it over if you want another set of eyes.

**Comment by DanielleMaywood** [comment]
Will get round to this later!

**Comment by MightyMoud** [comment]
No rush! 
Let's chat in the PR if you have any comments
