### ISSUE TITLE
Look at Dokku postgres-plugin for inspiration about DB management

### ISSUE THREAD

**Issue by gamedevsam** [MightyMoud/sidekick#21]
Dokku is an alternative self-hosting utility solution that offers similar things to what sidekick does, although I think sidekick offers a simpler interface and a reduced set of features that make it a compelling solution on its own.

When it comes times to implement DB support, I recommend you look at Dokku, because it's done really well: 

- PG: https://github.com/dokku/dokku-postgres
- MySQL: https://github.com/dokku/dokku-mariadb

**Comment by MightyMoud** [comment]
Hi @gamedevsam 
Love it! Very happy you think of Sidekick and Dokku at the same category! 😄 Makes me proud!
