### ISSUE TITLE
Run many processes inside the docker - like  what docker compose does .

### ISSUE THREAD

**Issue by gedw99** [MightyMoud/sidekick#22]
Often you want your docker to run many processes.

https://github.com/cirello-io/runner Does this off a Proc file .

it also supports formations .

the read e is self explanatory.

I use this locally , then I just copy my make file inside my docker and run everything there.
The makefile brings in all deps.

you can even add git wat her to watch for changes and just pull the source on a git eeb hook . So you don’t need to rerun docker from your laptop .

it also can watch for changes and then rebuild whatever is needed .

under the hood it uses supervision trees to watch all processes that are added to the proc file.

Because it works on any desktop you can if you want do all development outside a docker too .

So this might be useful in this project since it’s doing what docker compose does is my point ;)

it also has a simple web gui that is doing discovery and shows all logs for all processes .

unlike sidekick , I use caddy. It’s just one of the processes that runner runs . I normally set it up with cove security protections using xcsddy . Caddy git, do it watches my git for changes , and caddy cache to speed up anything I am running .

Love this project @MightyMoud

**Comment by MightyMoud** [comment]
Hey @gedw99,

Maybe this is what Fly.io uses? cus they also support `Procfile` I used it once on a project I deployed there.

I do have a question tho? In your case, why not use a docker compose file instead? I am planning to get Sidekick to support docker compose files. Or maybe you can use sidekick config to add "accessories" to your project, maybe a db or something else where Sidekick will make the docker compose for you and take care of the rest.

Wouldn't that be enough? if not, could you please elaborate more?

Cheers,
MM

**Comment by MightyMoud** [comment]
Closing this due to lack of response.
