### ISSUE TITLE
Add json out option to cli 

### ISSUE THREAD

**Issue by gedw99** [MightyMoud/sidekick#23]
I am looking to automate side kick with nats Jetstream so that I can automate side kick .

it will be way easier if in root we add the option of all commands having “—output json “ in https://github.com/MightyMoud/sidekick/blob/main/cmd/root.go

This is what GitHub cli has too . It makes it way easier to control it because you can just parse the json output from a global automation system like nats Jetstream .

thanks @MightyMoud for the great work .

**Comment by MightyMoud** [comment]
Interesting, I have honestly not heard about nats Jetstream before. 

I do get the idea of json out tho. However, can you tell me more about your use case? Just curious what kind of output would you like to parse? right now Sidekick just outputs success or failure message but no information really.
