### ISSUE TITLE
Launching fails silently when Sop is unable to parse an .env file

### ISSUE THREAD

**Issue by adampresley** [MightyMoud/sidekick#24]
The server machine:

- Ubuntu 24
- Sidekick is initialized and I can confirm Traefik is running
- I added Postgres to the sidekick docker compose file because I want it running

Client machine is running MacOS Sequoia.

The application is a Go application. I have a Dockerfile that builds successfully, and a environment variables file named `.env.production`. Here is a screenshot (with redactions). 

![CleanShot 2024-09-25 at 15 34 26@2x](https://github.com/user-attachments/assets/0c01e73d-2b2f-4f1b-8749-d724a05d7b1c)

What I'm seeing is that the launch appears successful. However, looking at running Docker processes, I don't see my new app container. 

![CleanShot 2024-09-25 at 15 37 35@2x](https://github.com/user-attachments/assets/865af396-d7d8-4a64-8102-fd5925dc33de)

So I looked over the code and see that you are using Sop to handle sending encrypted environment variables to the docker compose command. I tried running this manually and here is what I see.

![CleanShot 2024-09-25 at 15 38 22@2x](https://github.com/user-attachments/assets/5f130425-2f3e-4cd2-962a-8ac03a43ae09)

Are there any "gotchas" I should be aware of when using Sop with an environment file?

**Comment by MightyMoud** [comment]
Hi @adampresley 

I haven't come across this before. I'll replicate it tonight and do some testing.

But it seems to be reported before on sops side https://github.com/getsops/sops/issues/1128 & https://github.com/getsops/sops/issues/814

**Comment by MightyMoud** [comment]
@adampresley would this solve your issue? https://github.com/getsops/sops/issues/1157#issuecomment-1551548815
I am unable to replicate this issue currently. So it's really hard to work at it

**Comment by BraydenGirard** [comment]
I seem to get the issue no matter what I do. I tried wiping my server and starting fresh and after first deploy any subsequent deploy gives this issue. I don't believe it has anything to do with Windows line endings in my case as I am creating the project on Ubuntu 24.04 and deploying to a Ubuntu 24.04 server.

**Comment by BraydenGirard** [comment]
@MightyMoud if it helps I can add you onto my private repo so you can test with the same code base. Its a pocketbase project.

**Comment by MightyMoud** [comment]
> @MightyMoud if it helps I can add you onto my private repo so you can test with the same code base. Its a pocketbase project. 

That would be brilliant. Please do so. I'm struggling to replicate this.

**Comment by BraydenGirard** [comment]
@MightyMoud sent

**Comment by MightyMoud** [comment]
Thanks @BraydenGirard I'll have a look tomorrow evening

**Comment by MightyMoud** [comment]
@BraydenGirard just having a quick look at this, I can't seem to find the env file you are building with. 
Could we chat over email? m.mousa @ hey.com

**Comment by BraydenGirard** [comment]
> @BraydenGirard just having a quick look at this, I can't seem to find the env file you are building with. Could we chat over email? m.mousa @ hey.com

Email sent

**Comment by MightyMoud** [comment]
I am able to replicate this now by adding single quotes around the timestamp inside of the `encrypted.env` file.
This is mentioned here https://github.com/getsops/sops/issues/814
I'm still not sure how that single quote got there. 

@adampresley can you run `sops --version` & `age --version` on your local and let me know what version do you have?

**Comment by adampresley** [comment]
@MightyMoud Sure. Sops: sops 3.9.0. I don't have "age".

**Comment by MightyMoud** [comment]
Alright I can replicate this now. Thanks gents.
I'll push some changes soon. I think I will also overhaul the env handling method in Sidekick soon.

Stay tuned
