### ISSUE TITLE
Can you expend on the usage of sops and age?

### ISSUE THREAD

**Issue by VictorioBerra** [MightyMoud/sidekick#26]
Im new with these, the readme says:

> Use sops to decrypt your env file and start and env with the values injected

How/when are my .env files decrypted and passed to Docker?

**Comment by MightyMoud** [comment]
Hi @VictorioBerra

- During running `sidekick init` we make a private/public key encryption keypair using age [HERE](https://github.com/MightyMoud/sidekick/blob/0d37da54b10db6b3b5f6d49f53fa137e960db453/cmd/init.go#L110)
- We then store the public key into the config [HERE](https://github.com/MightyMoud/sidekick/blob/0d37da54b10db6b3b5f6d49f53fa137e960db453/cmd/init.go#L119)
- When running `sidekick launch` we will [encrypt](https://github.com/MightyMoud/sidekick/blob/0d37da54b10db6b3b5f6d49f53fa137e960db453/utils/scripts.go#L44) your env file into a file called `ecrypted.env` that will be moved to VPS. 
- Then they get [decrypted using sops](https://github.com/MightyMoud/sidekick/blob/0d37da54b10db6b3b5f6d49f53fa137e960db453/utils/scripts.go#L60) on a short lived env to run your docker compose command in. 

I'll document this soon on our new docs site. 

Cheers
