### ISSUE TITLE
sidekick deploy doesn't get quicker

### ISSUE THREAD

**Issue by semics-tech** [MightyMoud/sidekick#27]
When running `sidekick deploy` a second time it doesn't seem to get any quicker. Is it possible to output debug logs so I can see which step is taking the longest?

**Comment by MightyMoud** [comment]
I'm working on exposing the logs either by default or under a debug flag. Will keep you updated once it's released, but the TUI I use doesn't support the experience I want to make. So I'm searching for alternatives
