### ISSUE TITLE
Use without container image registry

### ISSUE THREAD

**Issue by lpil** [MightyMoud/sidekick#3]
Hello! Love what you're doing here! I really like the goals.

One thing I found a bit confusing given it seems to be about not relying on external services and complexity is that a docker registry is needed. Would it be possible to push the image directly to the server? Currently I do this using `docker save` and `docker load` in my scripts.

Thanks,
Louis

**Comment by diogox** [comment]
The above approach with `scp` under the hood to transfer the file would be great!

**Comment by MightyMoud** [comment]
Hey Louis,

Thanks for bringing this up. I never actually thought of it.
Fits perfectly in my vision for Sidekick.

I'll hash it out maybe during this weekend or throughout the next week.

Cheers,
Mahmoud

**Comment by lpil** [comment]
Wonderful! Thank you

**Comment by MightyMoud** [comment]
Alright this is now the default in Sidekick. Thanks for the suggestion dude
