### ISSUE TITLE
Multiple issues when creating an Ubuntu Server on Digital Ocean

### ISSUE THREAD

**Issue by darrylmorley** [MightyMoud/sidekick#33]
When using a fresh Ubuntu droplet on Digital Ocean and running `sidekick init`, I encountered the following issues:

- No SSH SOCK AVAILABLE
- Failed to read known_hosts: %!s(<nil>)
- Failed to create ssh client to the server: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Steps Taken:
- Ensured ssh-agent is running.
- Created a new known_hosts file in the .ssh directory using touch ~/.ssh/known_hosts.

Problem: I'm unable to proceed past the third issue, where the SSH client fails to authenticate and I'm unsure how to proceed at this point.

**Comment by darrylmorley** [comment]
Ahh, sidekick is supposed to be run on a client, not the VPS... I must be blind, I didn't notice this.

**Comment by LucaNerlich** [comment]
> Ahh, sidekick is supposed to be run on a client, not the VPS... I must be blind, I didn't notice this.

wait what? lol. Ive completly missed that as well. wow

I was wondering, why ive ran into so many issues...
