### ISSUE TITLE
Feedback: Possible name collision

### ISSUE THREAD

**Issue by mandarvaze** [MightyMoud/sidekick#35]
You might be already aware that there is very popular https://github.com/sidekiq/sidekiq in Ruby world.

I get that this project is :
- spelt differently
- Has  different purpose

I thought I should mention (and document, in case people come with similar feedback in future)

**Comment by MightyMoud** [comment]
Yes I am aware. 
Nothing to do with Sidekick
Sidekick is the correct way to spell the word in English.
