### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mrwyndham** [MightyMoud/sidekick#38]
Failed on the VPS not sure what the issue is. 

 SUCCESS  Logged in successfully!                                                                                                                                                                                 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105270b68]

goroutine 1 [running]:
golang.org/x/crypto/ssh.(*Client).NewSession(0x1054737e0?)
        golang.org/x/crypto@v0.24.0/ssh/client.go:134 +0x18
github.com/mightymoud/sidekick/utils.RunCommand(0x140001794e8?, {0x10538eb7c, 0x2d})
        github.com/mightymoud/sidekick/utils/utils.go:43 +0x3c
github.com/mightymoud/sidekick/utils.RunCommands(...)
        github.com/mightymoud/sidekick/utils/utils.go:91
github.com/mightymoud/sidekick/utils.RunStage(0x0, {{0x105818a40, 0x6, 0x6}, {0x105384e3f, 0x1d}, {0x10538ca92, 0x29}})
        github.com/mightymoud/sidekick/utils/utils.go:101 +0x74
github.com/mightymoud/sidekick/cmd.init.func4(0x140001dc100?, {0x1053786fe?, 0x4?, 0x105378702?})
        github.com/mightymoud/sidekick/cmd/init.go:92 +0xfe4
github.com/spf13/cobra.(*Command).execute(0x10581b720, {0x105849b20, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x10581bfc0)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/mightymoud/sidekick/cmd.Execute()
        github.com/mightymoud/sidekick/cmd/root.go:34 +0x24
main.main()
        github.com/mightymoud/sidekick/main.go:20 +0x1c

**Comment by MightyMoud** [comment]
Hi @mrwyndham ,

Are you able to ssh root@ip?

I'll fix this atrocious error message soon

**Comment by blinkinglight** [comment]
have you installed "sops" and "age" ?

**Comment by mrwyndham** [comment]
> Hi @mrwyndham ,
> 
> Are you able to ssh root@ip?
> 
> I'll fix this atrocious error message soon

Yeah I am able to

**Comment by mrwyndham** [comment]
> have you installed "sops" and "age" ?

Not intentionally. I am on M1 Macbook Pro and didn't change anything on Ubuntu linux vps

**Comment by MightyMoud** [comment]
@mrwyndham don't mind age and sops please.

Can you upgrade to latest version 0.6.3 and try again?
If you do get a nice error message saying a connection can't be established with the server, then could you let me know which key are you using to connect? sidekick will use the lookup order mentioned on the readme. Can you check that out?

**Comment by mrwyndham** [comment]
Ok did that and got

Welcome to Sidekick. We need to collect some details from you first


                                                                  ███████ ██ ██████  ███████ ██   ██ ██  ██████ ██   ██ 
                                                                  ██      ██ ██   ██ ██      ██  ██  ██ ██      ██  ██  
                                                                  ███████ ██ ██   ██ █████   █████   ██ ██      █████   
                                                                       ██ ██ ██   ██ ██      ██  ██  ██ ██      ██  ██  
                                                                  ███████ ██ ██████  ███████ ██   ██ ██  ██████ ██   ██ 
                                                                  
                                                                  
  ERROR   Sidekick config not found. Please run sidekick init.

**Comment by mrwyndham** [comment]
I uninstalled and reinstalled and still got the same thing I take it it's because the sidekick.toml file is missing somehow but I am not sure how to readd it

**Comment by MightyMoud** [comment]
@mrwyndham I think you have to nuke your VPS and try again with latest version.
Start off with `sidekick init` first off. 

let me know if you face any errors

**Comment by mrwyndham** [comment]
Yeah I did that as well. I'll try again tho

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MightyMoud** [comment]
Hmmm @mrwyndham send me an email, I need more details about your SSH Setup m.mousa @ hey.com

**Comment by mrwyndham** [comment]
My issue was that I had not used add SSH in the setup of my VPS. @MightyMoud helped me get it solved! Top bloke!

**Comment by MightyMoud** [comment]
Thanks @mrwyndham Glad that is solved now.
@gedw99 that is a separate issue. Next release will fix it
