### ISSUE TITLE
feat: remote building / skip building

### ISSUE THREAD

**Issue by oscarnevarezleal** [MightyMoud/sidekick#45]
## What?

This feature request proposes an enhancement to the launch command in Sidekick. The current workflow builds Docker images locally and transfers them to the VPS using scp. However, in certain scenarios, building the image remotely would significantly improve speed and efficiency. My ideal workflow for this feature would be:

1.	Build the image remotely on your own server or using tools like e.g [Depot](https://depot.dev/).
2.	Download and test the image locally.
3.	Deploy the tested image.

## Why is this necessary?

Rebuilding Docker images from scratch can be time-consuming, especially for complex setups like those involving LLM models or large dependencies. This remote build option would streamline deployments, saving time and reducing local system load.

## Improvement Areas

Adding specific launch flags could:

•	Automatically detect whether a rebuild is needed or if an existing image can be reused.
•	Offer flexible image handling tailored to different workflows and deployment needs.

**Comment by MightyMoud** [comment]
Hi @oscarnevarezleal,

Thank you for a very well formatted issue. ❤️

From the start of working on Sidekick I have been against building on remote machines. I think Coolify goes through that route. My reasons for this as follows:
- You need your source code to build an image - Your source code doesn't belong on your prod machine; only an image is needed.
- Extra added complexity for not added benefit - I want Sidekick to focus on working things out with just two machines; your local and your VPS. In most cases that is all you need.
(I will write more on the docs about those design decisions this week)

However, I do think you bring a good point especially if you are embedding a model into your image. I want to push back on this though; why are you embedding a model into the image? If you need a local model for your app, pull it down after deploy and then mount it to the machine as a volume. You would be able to do that with lifecycle hook, a feature planned for Sidekick later maybe Q1 next year.

The three steps you highlighted above are just too complicated. Also you should always try to make your image as simple as possible, as environment agnostic as possible and as code focused as possible; just your code and nothing else.

Let me know your thoughts.

**Comment by MightyMoud** [comment]
Forgot to add after all that: Sidekick has an issue with docker build cache currently that I'm still investigating. It's harder than it seems with the way we use the docker CLI sadly.

**Comment by oscarnevarezleal** [comment]
@MightyMoud thank you, I appreciate your comments.

My project serve inference endpoints and to be ready in seconds not minutes is essential. In the past I tried to download the models after the container is deployed but this is only add an extra layer of latency not to mention that sometimes the download could fail and then you end up with a new broken release. Just to give some some colors to the problem, we talk about 12-15GB for embedding models.

I love the idea of using volumes, that's a path I was considering using along with sidekick. I suppose I could use some user-data scripts to initialize the VPS.

Regarding the build cache, would you mind to elaborate in the problem/hardness of using cache during the building?

**Comment by MightyMoud** [comment]
I suggest you make another container to run just to download the model to a shared volume between that new container and your API application. Then once that container is healthy, finished download successfully, docker compose will bring up your API application online. You can read more about this here https://docs.docker.com/compose/how-tos/startup-order/

This is what I would do if I was in your shoes.

The way we run the build command is through the GO runtime. I have found out that this means the normal caching behaviour that you get when you run docker doesn't work. This is mostly because the GO run time requires a new shell env every time it tries to run a command. So the cache is not carried forward. There are ways to point docker build command to a specific local cache. 
I will attend to that at some point tho. Got bigger fish to fry now.

**Comment by oscarnevarezleal** [comment]
I appreciate your feedback, I will give it a try.
