### ISSUE TITLE
Support for multiple servers

### ISSUE THREAD

**Issue by TheNaubit** [MightyMoud/sidekick#46]
I am not sure if I am not looking in the right place and the feature is already there, but if not, it could be awesome to support multiple servers.

For example, when you run `sidekick launch` being able to pick to which VPS to deploy.

**Comment by MightyMoud** [comment]
Hey buddy, 
It's planned. Will do that after the db features first

Cheers

**Comment by TheNaubit** [comment]
Thank you, the project has been really useful already!

**Comment by MightyMoud** [comment]
Thank you. 
Closing this to clean thing sup
