### ISSUE TITLE
Some 404 on documentation page

### ISSUE THREAD

**Issue by alxdsz** [MightyMoud/sidekick#48]
Hi!

Kudos for the project, very nice approach :)

Skimmed through your docs and found out that some of the pages result in 404. Perhaps it's just a work in progress and you are aware of this, so you might just ignore it for now but I thought it doesn't cost pinging you about that :)

The ones I've found:
`/docs/introduction/get-started/ethos/principles#no-magic`
`/commands/init`

Cheers!

**Comment by MightyMoud** [comment]
Much appreciated @alxdsz 

The docs need a lot more work tbh. I'm doing that in the next couple of days. 
I would really appreciate if you can report anything else you notice.

Thank you! ❤️

**Comment by aramnhammer** [comment]
Adding to the list:
- https://www.sidekickdeploy.com/commands/init

**Comment by MightyMoud** [comment]
Thank you both. Just pushed a fix. 🎉
