### ISSUE TITLE
Fails silently with: "building with "desktop-linux" instance using docker driver"

### ISSUE THREAD

**Issue by chillbert** [MightyMoud/sidekick#50]
<img width="604" alt="image" src="https://github.com/user-attachments/assets/b236cdd8-5ebc-42ba-9429-5e121e5d9204">
                                                                   
                     Launching your application on your VPS 🚀                     
                                                                                   
                                                                                   
 ✔ VPS is reachable                                                                
 ⚠ Building latest docker image of your app                                        
 └── #0 building with "desktop-linux" instance using docker driver                 
                                                                                   
  󰚭 Saving docker image locally                                                    
  󰚭 Moving image to your server                                                    
  󰚭 Setting up your application                 

and now what?

I am on a macbook Apple M3 Max; MacOS Sonoma 14.6.1 (23G93).
My VPS is an Ubuntu 24

It is failing due to some npm packages in my nextjs app - but since the logs disapear I can't see what the problem is - is there a verbose launch for $sidekick launch?

**Comment by MightyMoud** [comment]
Hey buddy,

Make sure you have a docker file you can build first before running the launch command. 
So run docker build first for now. 

I'll add a verbose mode soon.

**Comment by chillbert** [comment]
Ah I see. Sorry didn't read the documentation completely. The docker build is failing locally... so nothing todo with sidekick. <3
