### ISSUE TITLE
Passing commands to the docker containers, mounting volumes, etc

### ISSUE THREAD

**Issue by daniel-abramov** [MightyMoud/sidekick#51]
First, thanks for the awesome project. The idea sounds really cool and useful! (to me it feels like a modern alternative to `dokku` 🙂)

I think it would also be cool if we could pass a command to the containers that are going to be run on VPS. E.g. in my case I'd need to also mount some docker volumes, local directories etc, which seemingly is not possible now. That being said, my feature request would not make much sense once an already existing roadmap item gets implemented, namely:

> A way to deploy more complicated projects defined in docker compose file

... as having a docker-compose file would allow configuring everything one can imagine.

**Comment by MightyMoud** [comment]
Hey @daniel-abramov,

Currently there's o way to do that. I'm planning a Hooks feature that will tackle that exactly. In my vision you wouldn't need to mount columns or do basic docker stuff with hooks. Those will be integrated into the normal workflow as part of something focused on end result; like deploying a DB instance. 

Hooks will be more for custom stuff.
