### ISSUE TITLE
Support for VPS over tailscale

### ISSUE THREAD

**Issue by aramnhammer** [MightyMoud/sidekick#52]
Seems that Sidekick fails to provision a VPS exposed through tailscale:
<img width="804" alt="image" src="https://github.com/user-attachments/assets/91f49fd5-182b-43a3-a874-6a206f24b5c3">

Not sure if this is out of scope or expected behavior.

**Comment by MightyMoud** [comment]
This IP address has already been saved on your machine with another signature. It's in `~/.ssh/known_hosts` you would need to clear that out first as long as this is a fresh VPS. Otherwise something phishy is going on. You can read more about MitM attacks
