### ISSUE TITLE
Unable to launch a new app

### ISSUE THREAD

**Issue by semics-tech** [MightyMoud/sidekick#66]
I used sidekick prevously to eventually get a container deployed on my server. 

I need to now deploy another app to the server but I kept getting the error `Failed to create ssh client to the server: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain` 

I upgraded from v0.6.0 to 0.6.6 now I am getting the following error running `sidekick launch`

```
2:09PM ERRO Backward Compat: Recent changes to how Sidekick handles secrets prevents you from launcing a new application.
2:09PM INFO Backward Compat: To fix this, run `Sidekick init` with the same server address you have now.
2:09PM INFO Backward Compat: Learn more at www.sidekickdeploy.com/docs/design/encryption
```

When trying to re-init the server with `sidekick init` I kept hitting the error below.

```
ERROR   Unable to establish SSH connection to the server
```

I realised I need to re-enable root login for the server for this to work. Once I did that was able to run `sidekick init` which failed a bit further on

```
 SUCCESS  Installed local requirements successfully
 SUCCESS  Logged in successfully!
 SUCCESS  New user created successfully
. Logging into with sidekick user
. Setting up VPS
. Setting up Docker
. Setting up Traefik
2024/11/16 14:12:20 Logging in failed with all available keys for the said user
```

I am able to login with the root user using `ssh` no problem and so not sure why it's not succeding.

1. Would it be possible to improve the error output, there is very little to say what is wrong i.e. "Could not login with root user, please try manually ssh root@<IP>" would be so much better than "ERROR   Unable to establish SSH connection to the server"
2. I'm not unable to use this because it says login failed, I'm not sure if it's trying to login with root or sidekick but I can't ssh with the sidekick user as I don't have the password.

**Comment by zeornelas** [comment]
Not sure if this helps, but you should be able to ssh with `sidekick@` with the same key you were using to `ssh root@`.
Then, you should be able to clean things up a little bit and `init` again. I don't think the whole ssh works with passwords.

Having this said, it would be great to have the logging part improved.

**Comment by semics-tech** [comment]
@zeornelas that worked but it took a while for me to configure the user to be able to ssh without a password (folder permissions, creating a local sidekick user & changing the password for the sidekick user on the server).

I know it is nice with passwordless ssh access but wouldn't a password fallback would make sense?
