### ISSUE TITLE
[Feature Request]: Add option to host the registry from the VPS

### ISSUE THREAD

**Issue by barelyhuman** [MightyMoud/sidekick#8]
https://hub.docker.com/_/registry , is a OCI container registry that can handle basic auth and distribution, could it be possible to just have sidekick setup the same and integrate with it to save some time. The docker hub and github registries are nice to maintain images for the public but for private and preview/test deployments publishing to docker becomes a chore which could be avoided if we could just push to the VPS instead. 

You can already do this by saving, copying the image tar, and loading the image and that's what I normally do but it'd be a nice optional(opt-in) addition for self hosting

**Comment by MightyMoud** [comment]
Hey @barelyhuman,

I like the idea of copying and pasting the image tar. I'll work on that soon. I think it's more aligned with the vision I have for Sidekick. 

Is your thinking that you want to host your own container registry so other projects, out of this single VPS, use it? If so I think you can achieve that with a docker compose file when I rollout support for that soon.

**Comment by barelyhuman** [comment]
> I like the idea of copying and pasting the image tar. I'll work on that soon. I think it's more aligned with the vision I have for Sidekick.

It works great as long as the images aren't worth GBs, in which case you might want to use something like `DOCKER_HOST` and use that to push instead of the image. 

> Is your thinking that you want to host your own container registry so other projects, out of this single VPS, use it? If so I think you can achieve that with a docker compose file when I rollout support for that soon.

Was more as an expansion to the project itself, since it could then have faster deploys since the images would be local but I understand the effort would be a bit more to keep it streamlined. 

The image tar and docker compose running Caddy is what I use for https://goblin.run right now, found about Sidekick looking for alternative ways to do that

**Comment by MightyMoud** [comment]
Yeah gotcha!

I think I will consider having this an option when you run `init` maybe. It's a bit more involved to setup. 
For now I will migrate the default to copying and loading images as default. 

I think Sidekick can help you with Goblin tho, but if you already have things setup maybe no added value for now.

**Comment by barelyhuman** [comment]
I did already setup another server with sidekick will migrate a few other projects to have a common deploy flow. 

Thanks for the project 👌🙏

**Comment by MightyMoud** [comment]
Thanks man. That makes my day! ❤️
